
project_id = "olbfnauhzpdskqnxtwav"

[functions]
[functions.assign-user-role]
verify_jwt = true

[functions.manage-entity]
verify_jwt = true

[functions.get-dashboard-data]
verify_jwt = true

[functions.invalidate-cache]
verify_jwt = true
