
project_id = "olbfnauhzpdskqnxtwav"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions]
function_timeout_seconds = 60

[functions.get_all_users_with_roles]
verify_jwt = true

[functions.get-all-users]
verify_jwt = true

[functions.assign-existing-user-as-sector-admin]
verify_jwt = true

[functions.assign-sector-admin]
verify_jwt = true

[functions.direct-login]
verify_jwt = false
