
# This is a sample supabase config.toml file.
# Unlike .env files, TOML allows for nested configuration, which supabase config requires.

project_id = "olbfnauhzpdskqnxtwav"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPV4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true
double_confirm_changes = true
double_confirm_changes_email = true

# JWT skladi supabase auth
[auth.jwt]
enabled = true

# auth redirect url nizamlamalari
[[auth.redirect_urls]]
url = "http://localhost:3000/login"

[[auth.redirect_urls]]
url = "http://localhost:3000/login-complete"

# Edge Function konfigurasyonu
[functions]
serve_port = 54324

[functions.safe-login]
verify_jwt = false # bu function auth olmadan erisile bilsin
port = 9999

[functions.get-user-role]
verify_jwt = true # bu function auth olmadan erisile bilmesin
port = 9998
