import React, { useState, useCallback } from 'react';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Edit, Copy, Download, Upload, File, FilePlus, AlertTriangle } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';
import { toast } from 'sonner';
import { CategoryWithColumns, Column } from '@/types/column';
import { Checkbox } from "@/components/ui/checkbox"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog"
import { useToast } from "@/components/ui/use-toast"
import { useAuth } from '@/context/auth';
import { useForm } from 'react-hook-form';
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { DatePicker } from "@/components/ui/date-picker"
import { CalendarIcon } from "@radix-ui/react-icons"
import { cn } from "@/lib/utils"
import { format } from "date-fns"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Separator } from "@/components/ui/separator"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Slider } from "@/components/ui/slider"
import { Switch } from "@/components/ui/switch"
import { Checkbox as ShadCheckbox } from "@/components/ui/checkbox"
import { Progress } from "@/components/ui/progress"
import { useSuperAdminDashboard } from '@/hooks/useSuperAdminDashboard';
import { useRegionAdminDashboard } from '@/hooks/useRegionAdminDashboard';
import { useSectorAdminDashboard } from '@/hooks/useSectorAdminDashboard';
import { useSchoolAdminDashboard } from '@/hooks/useSchoolAdminDashboard';
import { useDashboard } from '@/hooks/useDashboard';
import { useColumns } from '@/hooks/columns';
import { useCategories } from '@/hooks/categories/useCategories';
import { useDataEntries } from '@/hooks/dataEntry/useDataEntries';
import { useSchool } from '@/hooks/dataEntry/useSchool';
import { useSearchParams } from 'react-router-dom';
import { adaptValidationRules } from '@/utils/typeMappings';
import { supabase } from '@/integrations/supabase/client';
import { ColumnType } from '@/types/column';

interface SchoolColumnTableProps {
  categoryId: string;
  schoolId: string;
}

const SchoolColumnTable: React.FC<SchoolColumnTableProps> = ({ categoryId, schoolId }) => {
  const { t } = useLanguage();
  const [searchParams, setSearchParams] = useSearchParams();
  const [isImportDialogOpen, setIsImportDialogOpen] = useState(false);
  const [isTemplateDialogOpen, setIsTemplateDialogOpen] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  const [isGeneratingTemplate, setIsGeneratingTemplate] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isDirty, setIsDirty] = useState(false);
  const [entries, setEntries] = useState<any[]>([]);
  const [columns, setColumns] = useState<Column[]>([]);
  const [category, setCategory] = useState<CategoryWithColumns | null>(null);
  const [validationErrors, setValidationErrors] = useState<{ [key: string]: string }>({});
  const [isReadOnly, setIsReadOnly] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isApproving, setIsApproving] = useState(false);
  const [isRejecting, setIsRejecting] = useState(false);
  const [rejectionReason, setRejectionReason] = useState('');
  const [isApprovalDialogOpen, setIsApprovalDialogOpen] = useState(false);
  const [isRejectionDialogOpen, setIsRejectionDialogOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isImportWithTemplateDialogOpen, setIsImportWithTemplateDialogOpen] = useState(false);
  const [templateFile, setTemplateFile] = useState<File | null>(null);
  const [isImportWithTemplateLoading, setIsImportWithTemplateLoading] = useState(false);
  const [isImportWithTemplateSuccess, setIsImportWithTemplateSuccess] = useState(false);
  const [isImportWithTemplateError, setIsImportWithTemplateError] = useState(false);
  const [importWithTemplateErrorMessage, setImportWithTemplateErrorMessage] = useState('');
  const [isImportWithTemplateProcessing, setIsImportWithTemplateProcessing] = useState(false);
  const [importWithTemplateProgress, setImportWithTemplateProgress] = useState(0);
  const [isImportWithTemplateCompleted, setIsImportWithTemplateCompleted] = useState(false);
  const [importWithTemplateResults, setImportWithTemplateResults] = useState<any[]>([]);
  const [isImportWithTemplateResultsDialogOpen, setIsImportWithTemplateResultsDialogOpen] = useState(false);
  const [isImportWithTemplateResultsError, setIsImportWithTemplateResultsError] = useState(false);
  const [importWithTemplateResultsErrorMessage, setImportWithTemplateResultsErrorMessage] = useState('');
  const [isImportWithTemplateResultsSuccess, setIsImportWithTemplateResultsSuccess] = useState(false);
  const [importWithTemplateResultsSuccessMessage, setImportWithTemplateResultsSuccessMessage] = useState('');
  const [isImportWithTemplateResultsWarning, setIsImportWithTemplateResultsWarning] = useState(false);
  const [importWithTemplateResultsWarningMessage, setImportWithTemplateResultsWarningMessage] = useState('');
  const [isImportWithTemplateResultsWarningCount, setImportWithTemplateResultsWarningCount] = useState(0);
  const [isImportWithTemplateResultsSuccessCount, setImportWithTemplateResultsSuccessCount] = useState(0);
  const [isImportWithTemplateResultsErrorCount, setImportWithTemplateResultsErrorCount] = useState(0);
  const [isImportWithTemplateResultsTotalCount, setImportWithTemplateResultsTotalCount] = useState(0);
  const [isImportWithTemplateResultsSkippedCount, setImportWithTemplateResultsSkippedCount] = useState(0);
  const [isImportWithTemplateResultsSkippedMessage, setImportWithTemplateResultsSkippedMessage] = useState('');
  const [isImportWithTemplateResultsSkipped, setIsImportWithTemplateResultsSkipped] = useState(false);
  const [isImportWithTemplateResultsSkippedDialogOpen, setIsImportWithTemplateResultsSkippedDialogOpen] = useState(false);
  const [isImportWithTemplateResultsSkippedMessageDialogOpen, setIsImportWithTemplateResultsSkippedMessageDialogOpen] = useState(false);
  const [isImportWithTemplateResultsSkippedMessageDialogMessage, setImportWithTemplateResultsSkippedMessageDialogMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogTitle, setImportWithTemplateResultsSkippedMessageDialogTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogType, setImportWithTemplateResultsSkippedMessageDialogType] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIcon, setImportWithTemplateResultsSkippedMessageDialogIcon] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconColor, setImportWithTemplateResultsSkippedMessageDialogIconColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconTitle, setImportWithTemplateResultsSkippedMessageDialogIconTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconDescription, setImportWithTemplateResultsSkippedMessageDialogIconDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageDescription] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageColor] = useState<'success' | 'warning' | 'error'>('success');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle, setImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageTitle] = useState('');
  const [isImportWithTemplateResultsSkippedMessageDialogIconMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessageMessage
