
import React, { createContext, useState, useContext, ReactNode, useEffect, useCallback } from 'react';

// Dil tiplərini müəyyən edirik
export type Language = 'az' | 'en' | 'ru' | 'tr';

// Dil məlumatları interfeysi
interface LanguageInfo {
  nativeName: string;
  flag: string;
}

// Dil seçimləri
const languageOptions: Record<Language, LanguageInfo> = {
  az: { nativeName: 'Azərbaycan', flag: '🇦🇿' },
  en: { nativeName: 'English', flag: '🇬🇧' },
  ru: { nativeName: 'Русский', flag: '🇷🇺' },
  tr: { nativeName: 'Türkçe', flag: '🇹🇷' }
};

// Tərcümələr
const translations: Record<Language, Record<string, string>> = {
  az: {
    selectLanguage: 'Dil seçin',
    dashboard: 'Əsas panel',
    sectors: 'Sektorlar',
    regions: 'Regionlar',
    schools: 'Məktəblər',
    categories: 'Kateqoriyalar',
    columns: 'Sütunlar',
    users: 'İstifadəçilər',
    reports: 'Hesabatlar',
    settings: 'Parametrlər',
    logout: 'Çıxış',
    noDataAvailable: 'Məlumat mövcud deyil',
    name: 'Ad',
    description: 'Açıqlama',
    createdAt: 'Yaradılma tarixi',
    updatedAt: 'Yenilənmə tarixi',
    status: 'Status',
    priority: 'Prioritet',
    actions: 'Əməliyyatlar',
    edit: 'Redaktə et',
    delete: 'Sil',
    active: 'Aktiv',
    inactive: 'Passiv',
    all: 'Hamısı',
    sectorsAssignment: 'Sektorlara təyin et',
    areYouSure: 'Əminsiniz?',
    confirmDelete: 'Silmək istədiyinizə əminsiniz?',
    cancel: 'Ləğv et',
    deleteConfirmationMessage: 'Bu məlumatı silmək istədiyinizə əminsiniz?',
    deleteSuccess: 'Məlumat uğurla silindi',
    deleteFailed: 'Məlumat silinərkən xəta baş verdi',
    editSuccess: 'Məlumat uğurla redaktə edildi',
    editFailed: 'Məlumat redaktə edilərkən xəta baş verdi',
    createSuccess: 'Məlumat uğurla yaradıldı',
    createFailed: 'Məlumat yaradılarkən xəta baş verdi',
    saveChanges: 'Dəyişiklikləri saxla',
    create: 'Yarat',
    search: 'Axtar',
    reset: 'Sıfırla',
    apply: 'Tətbiq et',
    filters: 'Filtrlər',
    showArchived: 'Arxivləri göstər',
    archived: 'Arxivlənmiş',
    unarchived: 'Arxivdən çıxarılmış',
    archiveSuccess: 'Məlumat uğurla arxivləndi',
    archiveFailed: 'Məlumat arxivlənərkən xəta baş verdi',
    unarchiveSuccess: 'Məlumat uğurla arxivdən çıxarıldı',
    unarchiveFailed: 'Məlumat arxivdən çıxarılarkən xəta baş verdi',
    noMatchingRecordsFound: 'Uyğun məlumat tapılmadı',
    loading: 'Yüklənir...',
    language: 'Dil',
    
    // Data entry page
    dataEntry: 'Məlumatların daxil edilməsi',
    enterDataAndSubmit: 'Məlumatları daxil edin və təsdiq üçün göndərin',
    saving: 'Saxlanılır',
    lastSaved: 'Son saxlanma',
    save: 'Saxla',
    saveDataManually: 'Məlumatları əl ilə saxlayın',
    submitForApproval: 'Təsdiq üçün göndər',
    submitForApprovalTooltip: 'Məlumatları təsdiqləmək üçün göndərin',
    help: 'Yardım',
    error: 'Xəta',
    fillAllRequiredFields: 'Zəhmət olmasa bütün məcburi sahələri doldurun',
    categorySaved: 'Kateqoriya saxlanıldı',
    currentCategorySaved: 'Cari kateqoriyanın məlumatları saxlanıldı',
    downloadingTemplate: 'Şablon endirilir',
    downloadingCategoryTemplate: 'Cari kateqoriya üçün Excel şablonu endirilir',
    formData: 'Forma məlumatları',
    approved: 'Təsdiqlənmiş',
    rejected: 'Rədd edilmiş',
    completion: 'Tamamlanma',
    completed: 'Tamamlanmış',
    category: 'Kateqoriya',
    excelTemplate: 'Excel şablonu',
    downloadAllTemplate: 'Tam şablonu endir',
    downloadCurrentTemplate: 'Hazırkı kateqoriya şablonunu endir',
    uploadWithExcel: 'Excel ilə yüklə',
    uploading: 'Yüklənir...',
    excelDataUploaded: 'Excel məlumatları yükləndi',
    dataSuccessfullyUploaded: 'Məlumatlar uğurla yükləndi və formaya tətbiq edildi',
    categoryExcelTemplateDownloaded: 'Kateqoriya Excel şablonu endirildi',
    categoryTemplateDownloaded: 'kateqoriyası üçün şablon endirildi',
    excelTemplateDownloaded: 'Excel şablonu endirildi',
    canUploadAfterFilling: 'Doldurduqdan sonra yükləyə bilərsiniz',
    categoryDataUploaded: 'Kateqoriya məlumatları yükləndi',
    categoryDataSuccessfullyUploaded: 'kateqoriyası üçün məlumatlar uğurla yükləndi',
    uploadCompleteForm: 'Tam formanı yüklə',
    uploadCurrentCategoryOnly: 'Yalnız cari kateqoriyanı yüklə',
    submissionSuccess: 'Göndərmə uğurlu oldu',
    submissionDescription: 'Məlumatlarınız təsdiq üçün göndərildi',
    dataPendingApproval: 'Məlumatlar təsdiq gözləyir',
    dataBeingReviewed: 'Məlumatlarınız yoxlanılır və tezliklə təsdiqlənəcək',
    dataApproved: 'Məlumatlar təsdiqləndi',
    dataApprovedDesc: 'Bütün məlumatlarınız təsdiqlənmişdir və düzəliş edilə bilməz',
    formHasErrors: 'Formada xətalar var',
    andOtherErrors: 'və digər xətalar',
    deadline: 'Son tarix',
    saveCategory: 'Kateqoriyanı saxla',
    categoryRejected: 'Kateqoriya rədd edildi',
    fixErrorsAndResubmit: 'Zəhmət olmasa xətaları düzəldin və yenidən göndərin',
    categoryApproved: 'Kateqoriya təsdiqləndi',
    categoryApprovedDesc: 'Bu kateqoriyanın məlumatları təsdiqlənib və artıq dəyişdirilə bilməz',
    rejectionReason: 'Rədd etmə səbəbi',
    changesAutoSaved: 'Dəyişikliklər avtomatik saxlanıldı',
    aboutDataEntry: 'Məlumatların daxil edilməsi haqqında',
    helpTip1: 'Bütün məcburi sahələri doldurun (*)',
    helpTip2: 'Məlumatlar avtomatik saxlanılır',
    helpTip3: 'Məlumatları Excel faylı ilə daxil edə bilərsiniz',
    helpTip4: 'Məlumatları təsdiq üçün göndərdikdən sonra dəyişdirmək mümkün deyil',
    helpTip5: 'Məlumatları daxil edərkən tərcümə elementləri üçün dil dəyişdirə bilərsiniz',
    helpTip6: 'Son tarixlər keçdikdə bildiriş alacaqsınız',
    helpTip7: 'Problem yaşadıqda texniki dəstəklə əlaqə saxlayın',
    understood: 'Başa düşdüm',
    confirm: 'Təsdiq et',
    submitWarning: 'Məlumatlarınızı təsdiq üçün göndərmək istədiyinizə əminsiniz? Təsdiqləndikdən sonra düzəliş edə bilməyəcəksiniz.',
    resubmit: 'Yenidən göndər',
    sending: 'Göndərilir...',
    welcomeToDataEntry: 'Məlumat daxiletmə səhifəsinə xoş gəlmisiniz',
    welcomeToDataEntryDesc: 'Məlumatları daxil edərək təsdiq üçün göndərə bilərsiniz',
    deadlineApproaching: 'Son tarix yaxınlaşır',
    deadlineApproachingDesc: 'Bəzi kateqoriyaların son tarixi yaxınlaşır, zəhmət olmasa vaxtında tamamlayın',
    newCategoryAdded: 'Yeni kateqoriya əlavə edildi',
    newCategoryAddedDesc: 'Sistemə yeni kateqoriya əlavə edildi, zəhmət olmasa məlumatları daxil edin',
    formRejected: 'Forma rədd edildi',
    formRejectedDesc: 'Göndərdiyiniz form rədd edildi, səbəbi görmək üçün qeydləri yoxlayın',
    overdue: 'Vaxtı keçib',
    today: 'Bu gün',
    tomorrow: 'Sabah',
    daysLeft: 'gün qalıb',
    submitted: 'Göndərildi',
    forgotPassword: 'Şifrəni unutmusunuz?',
    resetPassword: 'Şifrəni sıfırla',
    password: 'Şifrə',
    email: 'E-poçt',
    login: 'Giriş'
  },
  en: {
    selectLanguage: 'Select Language',
    dashboard: 'Dashboard',
    sectors: 'Sectors',
    regions: 'Regions',
    schools: 'Schools',
    categories: 'Categories',
    columns: 'Columns',
    users: 'Users',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    noDataAvailable: 'No data available',
    name: 'Name',
    description: 'Description',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    status: 'Status',
    priority: 'Priority',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    sectorsAssignment: 'Sectors Assignment',
    areYouSure: 'Are you sure?',
    confirmDelete: 'Are you sure you want to delete?',
    cancel: 'Cancel',
    deleteConfirmationMessage: 'Are you sure you want to delete this data?',
    deleteSuccess: 'Data deleted successfully',
    deleteFailed: 'Failed to delete data',
    editSuccess: 'Data edited successfully',
    editFailed: 'Failed to edit data',
    createSuccess: 'Data created successfully',
    createFailed: 'Failed to create data',
    saveChanges: 'Save Changes',
    create: 'Create',
    search: 'Search',
    reset: 'Reset',
    apply: 'Apply',
    filters: 'Filters',
    showArchived: 'Show Archived',
    archived: 'Archived',
    unarchived: 'Unarchived',
    archiveSuccess: 'Data archived successfully',
    archiveFailed: 'Failed to archive data',
    unarchiveSuccess: 'Data unarchived successfully',
    unarchiveFailed: 'Failed to unarchive data',
    noMatchingRecordsFound: 'No matching records found',
    loading: 'Loading...',
    language: 'Language',
    
    // Data entry page translations (brief example)
    dataEntry: 'Data Entry',
    enterDataAndSubmit: 'Enter data and submit for approval',
    // ... Similar translation keys as above, but in English
    saving: 'Saving',
    lastSaved: 'Last Saved',
    save: 'Save',
    saveDataManually: 'Save Data Manually',
    submitForApproval: 'Submit for Approval',
    submitForApprovalTooltip: 'Submit data for approval',
    help: 'Help',
    error: 'Error',
    fillAllRequiredFields: 'Please fill all required fields',
    categorySaved: 'Category Saved',
    currentCategorySaved: 'Current category data saved',
    downloadingTemplate: 'Downloading Template',
    downloadingCategoryTemplate: 'Downloading Excel template for current category',
    formData: 'Form Data',
    approved: 'Approved',
    rejected: 'Rejected',
    completion: 'Completion',
    completed: 'Completed',
    category: 'Category',
    excelTemplate: 'Excel Template',
    downloadAllTemplate: 'Download Full Template',
    downloadCurrentTemplate: 'Download Current Category Template',
    uploadWithExcel: 'Upload with Excel',
    uploading: 'Uploading...',
    excelDataUploaded: 'Excel data uploaded',
    dataSuccessfullyUploaded: 'Data successfully uploaded and applied to the form',
    categoryExcelTemplateDownloaded: 'Category Excel template downloaded',
    categoryTemplateDownloaded: 'template downloaded for category',
    excelTemplateDownloaded: 'Excel template downloaded',
    canUploadAfterFilling: 'You can upload after filling',
    categoryDataUploaded: 'Category data uploaded',
    categoryDataSuccessfullyUploaded: 'data successfully uploaded for category',
    uploadCompleteForm: 'Upload Complete Form',
    uploadCurrentCategoryOnly: 'Upload Current Category Only',
    submissionSuccess: 'Submission Successful',
    submissionDescription: 'Your data has been submitted for approval',
    dataPendingApproval: 'Data Pending Approval',
    dataBeingReviewed: 'Your data is being reviewed and will be approved soon',
    dataApproved: 'Data Approved',
    dataApprovedDesc: 'All your data has been approved and cannot be edited',
    formHasErrors: 'Form Has Errors',
    andOtherErrors: 'and other errors',
    deadline: 'Deadline',
    saveCategory: 'Save Category',
    categoryRejected: 'Category Rejected',
    fixErrorsAndResubmit: 'Please fix the errors and resubmit',
    categoryApproved: 'Category Approved',
    categoryApprovedDesc: 'The data for this category has been approved and can no longer be changed',
    rejectionReason: 'Rejection Reason',
    changesAutoSaved: 'Changes Auto Saved',
    aboutDataEntry: 'About Data Entry',
    helpTip1: 'Fill in all required fields (*)',
    helpTip2: 'Data is saved automatically',
    helpTip3: 'You can enter data with an Excel file',
    helpTip4: 'You cannot change the data after submitting it for approval',
    helpTip5: 'You can change the language for translation elements while entering data',
    helpTip6: 'You will receive a notification when deadlines pass',
    helpTip7: 'Contact technical support if you have any problems',
    understood: 'Understood',
    confirm: 'Confirm',
    submitWarning: 'Are you sure you want to submit your data for approval? You will not be able to make corrections after approval.',
    resubmit: 'Resubmit',
    sending: 'Sending...',
    welcomeToDataEntry: 'Welcome to the data entry page',
    welcomeToDataEntryDesc: 'You can submit for approval by entering data',
    deadlineApproaching: 'Deadline Approaching',
    deadlineApproachingDesc: 'The deadline for some categories is approaching, please complete it in time',
    newCategoryAdded: 'New category added',
    newCategoryAddedDesc: 'A new category has been added to the system, please enter the information',
    formRejected: 'Form Rejected',
    formRejectedDesc: 'The form you submitted has been rejected, check the notes to see the reason',
    overdue: 'Overdue',
    today: 'Today',
    tomorrow: 'Tomorrow',
    daysLeft: 'days left',
    submitted: 'Submitted',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    password: 'Password',
    email: 'Email',
    login: 'Login'
  },
  ru: {
    selectLanguage: 'Выберите язык',
    dashboard: 'Главная панель',
    sectors: 'Секторы',
    regions: 'Регионы',
    schools: 'Школы',
    categories: 'Категории',
    columns: 'Столбцы',
    users: 'Пользователи',
    reports: 'Отчеты',
    settings: 'Настройки',
    logout: 'Выйти',
    noDataAvailable: 'Нет данных',
    name: 'Имя',
    description: 'Описание',
    createdAt: 'Создано',
    updatedAt: 'Обновлено',
    status: 'Статус',
    priority: 'Приоритет',
    actions: 'Действия',
    edit: 'Редактировать',
    delete: 'Удалить',
    active: 'Активный',
    inactive: 'Неактивный',
    all: 'Все',
    sectorsAssignment: 'Назначение секторам',
    areYouSure: 'Вы уверены?',
    confirmDelete: 'Вы уверены, что хотите удалить?',
    cancel: 'Отмена',
    deleteConfirmationMessage: 'Вы уверены, что хотите удалить эти данные?',
    deleteSuccess: 'Данные успешно удалены',
    deleteFailed: 'Не удалось удалить данные',
    editSuccess: 'Данные успешно отредактированы',
    editFailed: 'Не удалось отредактировать данные',
    createSuccess: 'Данные успешно созданы',
    createFailed: 'Не удалось создать данные',
    saveChanges: 'Сохранить изменения',
    create: 'Создать',
    search: 'Поиск',
    reset: 'Сбросить',
    apply: 'Применить',
    filters: 'Фильтры',
    showArchived: 'Показать архивированные',
    archived: 'Архивировано',
    unarchived: 'Разархивировано',
    archiveSuccess: 'Данные успешно архивированы',
    archiveFailed: 'Не удалось архивировать данные',
    unarchiveSuccess: 'Данные успешно разархивированы',
    unarchiveFailed: 'Не удалось разархивировать данные',
    noMatchingRecordsFound: 'Совпадений не найдено',
    loading: 'Загрузка...',
    language: 'Язык',
    
    // Data entry page translations (brief example)
    dataEntry: 'Ввод данных',
    enterDataAndSubmit: 'Введите данные и отправьте на утверждение',
    // ... Similar translation keys as above, but in Russian
    saving: 'Сохранение',
    lastSaved: 'Последнее сохранение',
    save: 'Сохранить',
    saveDataManually: 'Сохранить данные вручную',
    submitForApproval: 'Отправить на утверждение',
    submitForApprovalTooltip: 'Отправить данные на утверждение',
    help: 'Помощь',
    error: 'Ошибка',
    fillAllRequiredFields: 'Пожалуйста, заполните все обязательные поля',
    categorySaved: 'Категория сохранена',
    currentCategorySaved: 'Данные текущей категории сохранены',
    downloadingTemplate: 'Загрузка шаблона',
    downloadingCategoryTemplate: 'Загрузка Excel шаблона для текущей категории',
    formData: 'Данные формы',
    approved: 'Утверждено',
    rejected: 'Отклонено',
    completion: 'Завершение',
    completed: 'Завершено',
    category: 'Категория',
    excelTemplate: 'Excel шаблон',
    downloadAllTemplate: 'Скачать полный шаблон',
    downloadCurrentTemplate: 'Скачать шаблон текущей категории',
    uploadWithExcel: 'Загрузить с помощью Excel',
    uploading: 'Загрузка...',
    excelDataUploaded: 'Данные Excel загружены',
    dataSuccessfullyUploaded: 'Данные успешно загружены и применены к форме',
    categoryExcelTemplateDownloaded: 'Загружен шаблон Excel категории',
    categoryTemplateDownloaded: 'шаблон загружен для категории',
    excelTemplateDownloaded: 'Excel шаблон загружен',
    canUploadAfterFilling: 'Вы можете загрузить после заполнения',
    categoryDataUploaded: 'Данные категории загружены',
    categoryDataSuccessfullyUploaded: 'данные успешно загружены для категории',
    uploadCompleteForm: 'Загрузить полную форму',
    uploadCurrentCategoryOnly: 'Загрузить только текущую категорию',
    submissionSuccess: 'Отправка успешна',
    submissionDescription: 'Ваши данные отправлены на утверждение',
    dataPendingApproval: 'Данные ожидают утверждения',
    dataBeingReviewed: 'Ваши данные проверяются и скоро будут утверждены',
    dataApproved: 'Данные утверждены',
    dataApprovedDesc: 'Все ваши данные утверждены и не могут быть изменены',
    formHasErrors: 'В форме есть ошибки',
    andOtherErrors: 'и другие ошибки',
    deadline: 'Срок',
    saveCategory: 'Сохранить категорию',
    categoryRejected: 'Категория отклонена',
    fixErrorsAndResubmit: 'Пожалуйста, исправьте ошибки и отправьте повторно',
    categoryApproved: 'Категория утверждена',
    categoryApprovedDesc: 'Данные для этой категории утверждены и больше не могут быть изменены',
    rejectionReason: 'Причина отклонения',
    changesAutoSaved: 'Изменения автоматически сохранены',
    aboutDataEntry: 'О вводе данных',
    helpTip1: 'Заполните все обязательные поля (*)',
    helpTip2: 'Данные сохраняются автоматически',
    helpTip3: 'Вы можете ввести данные с помощью файла Excel',
    helpTip4: 'Вы не можете изменить данные после отправки на утверждение',
    helpTip5: 'Вы можете изменить язык для элементов перевода при вводе данных',
    helpTip6: 'Вы получите уведомление, когда истечет срок',
    helpTip7: 'Свяжитесь с технической поддержкой, если у вас возникнут проблемы',
    understood: 'Понятно',
    confirm: 'Подтвердить',
    submitWarning: 'Вы уверены, что хотите отправить свои данные на утверждение? Вы не сможете вносить исправления после утверждения.',
    resubmit: 'Отправить повторно',
    sending: 'Отправка...',
    welcomeToDataEntry: 'Добро пожаловать на страницу ввода данных',
    welcomeToDataEntryDesc: 'Вы можете отправить на утверждение, введя данные',
    deadlineApproaching: 'Приближается срок',
    deadlineApproachingDesc: 'Срок действия некоторых категорий приближается, пожалуйста, завершите их вовремя',
    newCategoryAdded: 'Добавлена новая категория',
    newCategoryAddedDesc: 'В систему добавлена новая категория, пожалуйста, введите информацию',
    formRejected: 'Форма отклонена',
    formRejectedDesc: 'Отправленная вами форма была отклонена, проверьте примечания, чтобы увидеть причину',
    overdue: 'Просрочено',
    today: 'Сегодня',
    tomorrow: 'Завтра',
    daysLeft: 'дней осталось',
    submitted: 'Отправлено',
    forgotPassword: 'Забыли пароль?',
    resetPassword: 'Сбросить пароль',
    password: 'Пароль',
    email: 'Эл. почта',
    login: 'Вход'
  },
  tr: {
    selectLanguage: 'Dil Seçin',
    dashboard: 'Gösterge Paneli',
    sectors: 'Sektörler',
    regions: 'Bölgeler',
    schools: 'Okullar',
    categories: 'Kategoriler',
    columns: 'Sütunlar',
    users: 'Kullanıcılar',
    reports: 'Raporlar',
    settings: 'Ayarlar',
    logout: 'Çıkış',
    noDataAvailable: 'Veri Yok',
    name: 'Adı',
    description: 'Açıklama',
    createdAt: 'Oluşturulma Tarihi',
    updatedAt: 'Güncellenme Tarihi',
    status: 'Durum',
    priority: 'Öncelik',
    actions: 'Eylemler',
    edit: 'Düzenle',
    delete: 'Sil',
    active: 'Aktif',
    inactive: 'Pasif',
    all: 'Tümü',
    sectorsAssignment: 'Sektörlere Atama',
    areYouSure: 'Emin misiniz?',
    confirmDelete: 'Silmek istediğinizden emin misiniz?',
    cancel: 'İptal',
    deleteConfirmationMessage: 'Bu veriyi silmek istediğinizden emin misiniz?',
    deleteSuccess: 'Veri başarıyla silindi',
    deleteFailed: 'Veri silinirken hata oluştu',
    editSuccess: 'Veri başarıyla düzenlendi',
    editFailed: 'Veri düzenlenirken hata oluştu',
    createSuccess: 'Veri başarıyla oluşturuldu',
    createFailed: 'Veri oluşturulurken hata oluştu',
    saveChanges: 'Değişiklikleri Kaydet',
    create: 'Oluştur',
    search: 'Ara',
    reset: 'Sıfırla',
    apply: 'Uygula',
    filters: 'Filtreler',
    showArchived: 'Arşivlenmişleri Göster',
    archived: 'Arşivlenmiş',
    unarchived: 'Arşivden Çıkarılmış',
    archiveSuccess: 'Veri başarıyla arşivlendi',
    archiveFailed: 'Veri arşivlenirken hata oluştu',
    unarchiveSuccess: 'Veri başarıyla arşivden çıkarıldı',
    unarchiveFailed: 'Veri arşivden çıkarılırken hata oluştu',
    noMatchingRecordsFound: 'Eşleşen kayıt bulunamadı',
    loading: 'Yükleniyor...',
    language: 'Dil',
    
    // Data entry page translations (brief example)
    dataEntry: 'Veri Girişi',
    enterDataAndSubmit: 'Verileri girin ve onay için gönderin',
    // ... Similar translation keys as above, but in Turkish
    saving: 'Kaydediliyor',
    lastSaved: 'Son Kayıt',
    save: 'Kaydet',
    saveDataManually: 'Verileri Manuel Olarak Kaydet',
    submitForApproval: 'Onay İçin Gönder',
    submitForApprovalTooltip: 'Verileri onay için gönder',
    help: 'Yardım',
    error: 'Hata',
    fillAllRequiredFields: 'Lütfen tüm zorunlu alanları doldurun',
    categorySaved: 'Kategori Kaydedildi',
    currentCategorySaved: 'Mevcut kategori verileri kaydedildi',
    downloadingTemplate: 'Şablon İndiriliyor',
    downloadingCategoryTemplate: 'Mevcut kategori için Excel şablonu indiriliyor',
    formData: 'Form Verileri',
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
    completion: 'Tamamlama',
    completed: 'Tamamlandı',
    category: 'Kategori',
    excelTemplate: 'Excel Şablonu',
    downloadAllTemplate: 'Tam Şablonu İndir',
    downloadCurrentTemplate: 'Mevcut Kategori Şablonunu İndir',
    uploadWithExcel: 'Excel ile Yükle',
    uploading: 'Yükleniyor...',
    excelDataUploaded: 'Excel verileri yüklendi',
    dataSuccessfullyUploaded: 'Veriler başarıyla yüklendi ve forma uygulandı',
    categoryExcelTemplateDownloaded: 'Kategori Excel şablonu indirildi',
    categoryTemplateDownloaded: 'kategorisi için şablon indirildi',
    excelTemplateDownloaded: 'Excel şablonu indirildi',
    canUploadAfterFilling: 'Doldurduktan sonra yükleyebilirsiniz',
    categoryDataUploaded: 'Kategori verileri yüklendi',
    categoryDataSuccessfullyUploaded: 'verileri başarıyla yüklendi kategorisi için',
    uploadCompleteForm: 'Tam Formu Yükle',
    uploadCurrentCategoryOnly: 'Sadece Mevcut Kategoriyi Yükle',
    submissionSuccess: 'Gönderme Başarılı',
    submissionDescription: 'Verileriniz onay için gönderildi',
    dataPendingApproval: 'Veriler Onay Bekliyor',
    dataBeingReviewed: 'Verileriniz inceleniyor ve yakında onaylanacak',
    dataApproved: 'Veriler Onaylandı',
    dataApprovedDesc: 'Tüm verileriniz onaylandı ve düzenlenemez',
    formHasErrors: 'Formda Hatalar Var',
    andOtherErrors: 've diğer hatalar',
    deadline: 'Son Tarih',
    saveCategory: 'Kategoriyi Kaydet',
    categoryRejected: 'Kategori Reddedildi',
    fixErrorsAndResubmit: 'Lütfen hataları düzeltin ve tekrar gönderin',
    categoryApproved: 'Kategori Onaylandı',
    categoryApprovedDesc: 'Bu kategoriye ait veriler onaylandı ve artık değiştirilemez',
    rejectionReason: 'Reddetme Nedeni',
    changesAutoSaved: 'Değişiklikler Otomatik Kaydedildi',
    aboutDataEntry: 'Veri Girişi Hakkında',
    helpTip1: 'Tüm zorunlu alanları doldurun (*)',
    helpTip2: 'Veriler otomatik olarak kaydedilir',
    helpTip3: 'Excel dosyası ile veri girebilirsiniz',
    helpTip4: 'Onay için gönderdikten sonra verileri değiştiremezsiniz',
    helpTip5: 'Veri girerken çeviri öğeleri için dili değiştirebilirsiniz',
    helpTip6: 'Son tarihler geçtiğinde bildirim alacaksınız',
    helpTip7: 'Sorun yaşarsanız teknik destek ile iletişime geçin',
    understood: 'Anlaşıldı',
    confirm: 'Onayla',
    submitWarning: 'Verilerinizi onay için göndermek istediğinizden emin misiniz? Onaylandıktan sonra düzeltme yapamayacaksınız.',
    resubmit: 'Yeniden Gönder',
    sending: 'Gönderiliyor...',
    welcomeToDataEntry: 'Veri giriş sayfasına hoş geldiniz',
    welcomeToDataEntryDesc: 'Veri girerek onay için gönderebilirsiniz',
    deadlineApproaching: 'Son Tarih Yaklaşıyor',
    deadlineApproachingDesc: 'Bazı kategorilerin son tarihi yaklaşıyor, lütfen zamanında tamamlayın',
    newCategoryAdded: 'Yeni kategori eklendi',
    newCategoryAddedDesc: 'Sisteme yeni bir kategori eklendi, lütfen bilgileri girin',
    formRejected: 'Form Reddedildi',
    formRejectedDesc: 'Gönderdiğiniz form reddedildi, nedeni görmek için notları kontrol edin',
    overdue: 'Süresi Geçti',
    today: 'Bugün',
    tomorrow: 'Yarın',
    daysLeft: 'gün kaldı',
    submitted: 'Gönderildi',
    forgotPassword: 'Şifreyi unuttunuz mu?',
    resetPassword: 'Şifreyi Sıfırla',
    password: 'Şifre',
    email: 'E-posta',
    login: 'Giriş'
  }
};

// Context tipini müəyyən edirik
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: Record<Language, LanguageInfo>;
}

// Context-i yaradırıq
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider komponenti
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>((localStorage.getItem('language') as Language) || 'az');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    languages: languageOptions
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Context-i istifadə etmək üçün hook
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
